#!/usr/bin/env bash

echo "Running librefgen..."
cd ..
pdirectory=$(pwd)
cd AI-IntelArc-ArchLinux
echo "Regenerating LIBREF..."
echo "pdirectory=$pdirectory" > ./libref
echo "export LD_LIBRARY_PATH=$pdirectory/AI-IntelArc-ArchLinux/AI-IntelArc-ArchLinux_env/lib" >> ./libref
echo "export USE_XETLA=OFF" >> ./libref
echo "export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1" >> ./libref
echo "export SYCL_CACHE_PERSISTENT=1" >> ./libref
echo "source $pdirectory/AI-IntelArc-ArchLinux/AI-IntelArc-ArchLinux_env/bin/ipex-llm-init -g --device Arc" >> ./libref

echo "AIIAAL_update () {" >> ./libref
echo "    cd $pdirectory/AI-IntelArc-ArchLinux" >> ./libref
echo "    git switch main" >> ./libref
echo "    git reset --hard HEAD" >> ./libref
echo "    git pull" >> ./libref
echo "}" >> ./libref
echo "LIBREF regenerated."
