#!/usr/bin/env bash

AIIAAL_update_fooocus () {
  cd $pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux
  pip install --upgrade -r requirements_fooocus.txt
  cp -r --no-clobber "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/models/checkpoints/." "$pdirectory/AI-IntelArc-ArchLinux/shared/checkpoints/t2i"
  cp -r --no-clobber "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/models/loras/." "$pdirectory/AI-IntelArc-ArchLinux/shared/loras/t2i"
  cp -r --no-clobber "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/sdxl_styles/." "$pdirectory/AI-IntelArc-ArchLinux/shared/sdxl_styles/fooocus"
  cp -r --no-clobber "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/presets/fooocus/." "$pdirectory/AI-IntelArc-ArchLinux/shared/presets"
  git switch main
  git fetch --all
  git reset --hard origin/master
  git clean -f -d
  git pull
#  git merge '@{u}'
}

Intel_mods () {
  cd $pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux
  if grep -Fxq "import intel_extension_for_pytorch as ipex" launch.py
    then
      echo "Intel extensions found in launch.py...skipping"
    else
      sed -i 's|import sys|import sys\nimport intel_extension_for_pytorch as ipex\nimport intel_extension_for_transformers\nimport openvino|g' launch.py
  fi
  if grep -Fxq "https://download.pytorch.org/whl/cu121" launch.py
    then
      echo "URL for Intel version of pytorch found in launch.py...skipping"
    else
      sed -i 's|https://download.pytorch.org/whl/cu121|https://pytorch-extension.intel.com/release-whl/stable/xpu/us/|g' launch.py
  fi
  if grep -Fxq "torch==2.1.0 torchvision==0.16.0" launch.py
    then
      echo "Intel versions of pytorch-related packages found in launch.py...skipping"
    else
      sed -i 's|torch==2.1.0 torchvision==0.16.0|torch>=2.1.0.post2 torchvision>=0.16.0.post2 torchaudio>=2.1.0.post2 intel-extension-for-pytorch>=2.1.30+xpu oneccl_bind_pt>=2.1.300+xpu|g' launch.py
  fi
  if grep -Fxq "torchsde>=0.2.5" requirements_versions.txt
    then
      echo "torchsde version fix found in requirements_versions.txt...skipping"
    else
      sed -i 's|torchsde==0.2.5|torchsde>=0.2.5|g' requirements_versions.txt
  fi
  if grep -Fxq "transformers>=4.34.0" requirements_versions.txt
    then
      echo "torchsde version fix found in requirements_versions.txt...skipping"
    else
      sed -i 's|transformers==4.30.2|transformers>=4.34.0|g' requirements_versions.txt
  fi
rm -R "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/models/checkpoints"
rm -R "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/models/loras"
rm -R "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/wildcards"
rm -R "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/sdxl_styles"
#rm -R "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/presets"
ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/checkpoints/t2i" "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/models/checkpoints"
ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/loras/t2i" "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/models/loras"
ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/wildcards/fooocus" "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/wildcards"
ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/sdxl_styles/fooocus" "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/sdxl_styles"
#ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/presets/fooocus" "$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/presets"
cd $pdirectory
$pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux/user_customize_fooocus.sh
}

fooocus-exit () {
    kill $(pidof python $pdirectory/AI-IntelArc-ArchLinux/fooocus)
}
