#!/usr/bin/env bash

AIIAAL_update_fooocus () {
  cd $pdirectory/AI-IntelArc-ArchLinux/fooocus-IntelArc-ArchLinux
  git switch main
  git reset --hard HEAD
  git pull
  if grep -Fxq "import intel_extension_for_pytorch" launch.py
    then
      echo "Intel extensions found in launch.py...skipping"
    else
      sed -i 's|import sys|import sys\nimport intel_extension_for_pytorch|g' launch.py
  fi
  if grep -Fxq "https://download.pytorch.org/whl/cu121" launch.py
    then
      echo "URL for Intel version of pytorch found in launch.py...skipping"
    else
      sed -i 's|https://download.pytorch.org/whl/cu121|https://pytorch-extension.intel.com/release-whl/stable/xpu/us/|g' launch.py
  fi
  if grep -Fxq "torch==2.1.0 torchvision==0.16.0" launch.py
    then
      echo "Intel versions of pytorch-related packages found in launch.py...skipping"
    else
      sed -i 's|torch==2.1.0 torchvision==0.16.0|torch==2.1.0.post2 torchvision==0.16.0.post2 torchaudio==2.1.0.post2 intel-extension-for-pytorch==2.1.30+xpu oneccl_bind_pt==2.1.300+xpu|g' launch.py
  fi
}
