#!/usr/bin/env bash

AIIAAL_update_forge () {
  cd $pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux
  git switch main
  git reset --hard HEAD
  git pull

  cd modules

  if grep -Fxq "import intel_extension_for_pytorch as ipex" launch_utils.py
    then
      echo "Intel extensions found in launch.py...skipping"
    else
      sed -i 's|from modules_forge.config import always_disabled_extensions|from modules_forge.config import always_disabled_extensions\nimport intel_extension_for_pytorch as ipex\nimport intel_extension_for_transformers\nimport torch\nfrom diffusers import StableDiffusionPipeline|g' launch_utils.py
  fi



  if grep -Fxq "pip install torch>=2.1.0.post2 torchvision>=0.16.0.post2 torchaudio>=2.1.0.post2 intel-extension-for-pytorch>=2.1.30+xpu oneccl_bind_pt>=2.1.300+xpu" launch_utils.py
    then
      echo "Intel versions of pytorch-related packages found in launch.py...skipping"
    else
      sed -i 's|torch==2.0.0a0 intel-extension-for-pytorch==2.0.110+gitba7f6c1|torch>=2.1.0.post2 torchvision>=0.16.0.post2 torchaudio>=2.1.0.post2 intel-extension-for-pytorch>=2.1.30+xpu oneccl_bind_pt>=2.1.300+xpu|g' launch_utils.py
  fi

rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/models/Stable-diffusion"
rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/models/Lora"
#rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/wildcards"
rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/VAE"
#rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/sdxl_styles"
ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/checkpoints/t2i" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/models/Stable-diffusion"
ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/loras/t2i" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/models/Lora"
#ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/wildcards/forge" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/wildcards"
ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/VAEs" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/VAE"
#ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/sdxl_styles/forge" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/sdxl_styles"
cd $pdirectory
$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/user_customize_forge.sh
}

forge-exit () {
    kill $(pidof python $pdirectory/AI-IntelArc-ArchLinux/forge)
}
