#!/usr/bin/env bash

AIIAAL_update_forge () {
  cd $pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux
  git switch main
  git reset --hard HEAD
  git pull
  if grep -Fxq "import intel_extension_for_pytorch as ipex" launch.py
    then
      echo "Intel extensions found in launch.py...skipping"
    else
      sed -i 's|from modules import launch_utils|from modules import launch_utils\nimport intel_extension_for_pytorch as ipex\nimport intel_extension_for_transformers\nimport openvino|g' launch.py

rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/models/Stable-diffusion"
#rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/models/loras"
#rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/wildcards"
#rm -R "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/sdxl_styles"
ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/checkpoints/t2i" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/models/Stable-diffusion"
#ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/loras/t2i" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/models/loras"
#ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/wildcards/forge" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/wildcards"
#ln -sf "$pdirectory/AI-IntelArc-ArchLinux/shared/sdxl_styles/forge" "$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/sdxl_styles"
cd $pdirectory
$pdirectory/AI-IntelArc-ArchLinux/forge-IntelArc-ArchLinux/user_customize_forge.sh
}

forge-exit () {
    kill $(pidof python $pdirectory/AI-IntelArc-ArchLinux/forge)
}
